function check(form)

    {  
        var aejntrwpqqpntoqnetdfgsriutnposeintaejntrwpqqpntoqnetdfgsriutnposeintjsgnbljndxlfgjnhldrjnpodnrtgosprtghdgjsgnbljndsythsawekrnkerglsppooiqimwmazmxmfkxlfgjnhldrjnpodnrtgosprtghdg = "1"
        var aejntrwpqqpntoqnetdfgsriutnposeintjsgnbljndsythsawekrnkerglsppooiqimwmazmxmfkxlfgjnhldrjnpodnrtgosprtghdg = "a"
        var oieurhgpiuernrsythsawekrnkerglsppooiqimwmazmxmfkdkfvdnojnvdbgstsit=aejntrwpqqpntoqnetdfgsriutnposeintjsgnbljndsythsawekrnkerglsppooiqimwmazmxmfkxlfgjnhldrjnpodnrtgosprtghdg
        var aejntrwpqqpntoqnetdfgsriutnposeintjsgnbljndxlfgjnhldrjnpodnrtgosprtghdg = "g"

        var sdsgnsyjdtsaerynjfujfyunngfhdtstbdndtydyjdbsatryuoortnaewAAWFADVSTSTHRTdthftyujnfdtgbdrgbdftsdhtgjdgfbdfgbdthstghfvcxvcvbmjhkfghdftgdthddthsdsgnsyjdtssaerynjfujfyunngfhdtstbdndtydyjdbsatryuoortnsewAAWFADVSTSTHRTdthftyujnfdtgbdrgbdftsdhtgjdgfbdfgbdthstghfvucxvcvbmjhkfghdftgdthddth= aejntrwpqqpntoqnetdfgsriutnposeintjsgnbljndxlfgjnhldrjnpodnrtgosprtghdg
        var fyuungfhdtstbdnbtydyjdbsatryuooortnaewAAWFADVSTSTHRTdthftyujnfdtgbrgbdftsdntgjdgfbdfgbdlhstghfv = "e"
        var fyuungfhdtstbdnbtydyjdbsatryuooortnaewAAWFADVSTSTxdfbxdgnhlkmzvlkrpwreignsjdnfobsthsnfjabfjubnosknvkxjdgbtotgujbsrlngbgbrgbdftsdntgjdgfbdfgbdlhstghfv = aejntrwpqqpntoqnetdfgsriutnposeintaejntrwpqqpntoqnetdfgsriutnposeintjsgnbljndxlfgjnhldrjnpodnrtgosprtghdgjsgnbljndsythsawekrnkerglsppooiqimwmazmxmfkxlfgjnhldrjnpodnrtgosprtghdg
        var syjdtsaerynjfnjfyunngfhdtstbdndtydyjdbsatryucortnaewAAWFADVSTSTHRTdthftyujfdtgbdrgbdflsdhtgjdgfbdfgbdthstghfvcxvcvbmjhknfghdftgdthbdthfghyjsqpejpqwknrjnopmxpwewerbfwjenoqazxwedcwedcefvevrgbthynytumnuikuiolpuiyn = "b"
        var bsatryuoortnsewAAWFADeryrtyrwsthwsrthryuftukifrytukfthSYJDTHNSTSHRYJDTUJDTHBGBDR = oieurhgpiuernrsythsawekrnkerglsppooiqimwmazmxmfkdkfvdnojnvdbgstsit

        var sdsgnsyjdtsaerynjfujfyunngfhdtstbdndtydyjdbsatryuoortnaewAAWFADVSTSTHRTdthftyujnfdtgbdrgbdftsdhtgjdgfbdfgbdthstghfvcxvcvbmjhkfghdftgdthddth = sdsgnsyjdtsaerynjfujfyunngfhdtstbdndtydyjdbsatryuoortnaewAAWFADVSTSTHRTdthftyujnfdtgbdrgbdftsdhtgjdgfbdfgbdthstghfvcxvcvbmjhkfghdftgdthddthsdsgnsyjdtssaerynjfujfyunngfhdtstbdndtydyjdbsatryuoortnsewAAWFADVSTSTHRTdthftyujnfdtgbdrgbdftsdhtgjdgfbdfgbdthstghfvucxvcvbmjhkfghdftgdthddth
        var sdsgnsyjdtsaerynjfujfyunngfhdtstbdndtydyjdbsatryuoortnaewAAWFADVSTSTHRTdthftyujfdtgbdrgbdftsdhtgjdgfbdfgbdthstghfvcxvcvbmjhknfghdftgdthddth = fyuungfhdtstbdnbtydyjdbsatryuooortnaewAAWFADVSTSTHRTdthftyujnfdtgbrgbdftsdntgjdgfbdfgbdlhstghfv + fyuungfhdtstbdnbtydyjdbsatryuooortnaewAAWFADVSTSTxdfbxdgnhlkmzvlkrpwreignsjdnfobsthsnfjabfjubnosknvkxjdgbtotgujbsrlngbgbrgbdftsdntgjdgfbdfgbdlhstghfv
        var sdsgnsyjdtsaerynjfnjfyunngfhdtstbdndtydyjdbsatryucortnaewAAWFADVSTSTHRTdthftyujfdtgbdrgbdflsdhtgjdgfbdfgbdthstghfvcxvcvbmjhknfghdftgdthbdth = syjdtsaerynjfnjfyunngfhdtstbdndtydyjdbsatryucortnaewAAWFADVSTSTHRTdthftyujfdtgbdrgbdflsdhtgjdgfbdfgbdthstghfvcxvcvbmjhknfghdftgdthbdthfghyjsqpejpqwknrjnopmxpwewerbfwjenoqazxwedcwedcefvevrgbthynytumnuikuiolpuiyn
        var sdsgnsyjdtsaerynjfujfyuungfhdtstbdnbtydyjdbsatryuoortnaewAAWFADVSTSTHRTdthftyujnfdtgbdrgbdftsdhtgjdgfbdfgbdlhstghfvcxvcvbmjhkfghdftgdthddth = bsatryuoortnsewAAWFADeryrtyrwsthwsrthryuftukifrytukfthSYJDTHNSTSHRYJDTUJDTHBGBDR + syjdtsaerynjfnjfyunngfhdtstbdndtydyjdbsatryucortnaewAAWFADVSTSTHRTdthftyujfdtgbdrgbdflsdhtgjdgfbdfgbdthstghfvcxvcvbmjhknfghdftgdthbdthfghyjsqpejpqwknrjnopmxpwewerbfwjenoqazxwedcwedcefvevrgbthynytumnuikuiolpuiyn
        var sdsgnsyjdtsaerynjfujfyuungfhdtstbdnbtydyjdbsatryuooortnaewAAWFADVSTSTHRTdthftyujnfdtgbrgbdftsdntgjdgfbdfgbdlhstghfvcxvcvbmjhkfghdftgdthddth = fyuungfhdtstbdnbtydyjdbsatryuooortnaewAAWFADVSTSTHRTdthftyujnfdtgbrgbdftsdntgjdgfbdfgbdlhstghfv
        var sdsgnsyjdtsaerynjfnujfyuungfhdlstbdnbtydyjdbsatryuooortnaewAAWFADVSTSTHRTdthftyujnfdjgbrgbdftsdntgjdgfbdfgbdlhstghfvcxvcvbmjhkfghdftgdthddt = fyuungfhdtstbdnbtydyjdbsatryuooortnaewAAWFADVSTSTxdfbxdgnhlkmzvlkrpwreignsjdnfobsthsnfjabfjubnosknvkxjdgbtotgujbsrlngbgbrgbdftsdntgjdgfbdfgbdlhstghfv
        var sdsgnsyjdtssaerynjfujfyunngfhdtstbdndtydyjdbsatryuoortnsewAAWFADVSTSTHRTdthftyujnfdtgbdrgbdftsdhtgjdgfbdfgbdthstghfvucxvcvbmjhkfghdftgdthddth = bsatryuoortnsewAAWFADeryrtyrwsthwsrthryuftukifrytukfthSYJDTHNSTSHRYJDTUJDTHBGBDR
        var sdsgnsyjdtssaerynjfujfyunngfhdtstbdndtydyjdbsatryuoortnsewAAWFADVSTSTHRTdthftujnfdtgbdrgbdftsdhtgjdgfbdfgbdthstghfvucxvcvbmjhkfghdftgdthddth = sdsgnsyjdtsaerynjfujfyunngfhdtstbdndtydyjdbsatryuoortnaewAAWFADVSTSTHRTdthftyujnfdtgbdrgbdftsdhtgjdgfbdfgbdthstghfvcxvcvbmjhkfghdftgdthddthsdsgnsyjdtssaerynjfujfyunngfhdtstbdndtydyjdbsatryuoortnsewAAWFADVSTSTHRTdthftyujnfdtgbdrgbdftsdhtgjdgfbdfgbdthstghfvucxvcvbmjhkfghdftgdthddth + bsatryuoortnsewAAWFADeryrtyrwsthwsrthryuftukifrytukfthSYJDTHNSTSHRYJDTUJDTHBGBDR
        
     if(form.userid.value == sdsgnsyjdtsaerynjfujfyunngfhdtstbdndtydyjdbsatryuoortnaewAAWFADVSTSTHRTdthftyujnfdtgbdrgbdftsdhtgjdgfbdfgbdthstghfvcxvcvbmjhkfghdftgdthddth
        + sdsgnsyjdtsaerynjfujfyuungfhdtstbdnbtydyjdbsatryuoortnaewAAWFADVSTSTHRTdthftyujnfdtgbdrgbdftsdhtgjdgfbdfgbdlhstghfvcxvcvbmjhkfghdftgdthddth 
        + sdsgnsyjdtsaerynjfujfyuungfhdtstbdnbtydyjdbsatryuooortnaewAAWFADVSTSTHRTdthftyujnfdtgbrgbdftsdntgjdgfbdfgbdlhstghfvcxvcvbmjhkfghdftgdthddth && form.pswrd.value == sdsgnsyjdtssaerynjfujfyunngfhdtstbdndtydyjdbsatryuoortnsewAAWFADVSTSTHRTdthftujnfdtgbdrgbdftsdhtgjdgfbdfgbdthstghfvucxvcvbmjhkfghdftgdthddth 
        + sdsgnsyjdtsaerynjfnjfyunngfhdtstbdndtydyjdbsatryucortnaewAAWFADVSTSTHRTdthftyujfdtgbdrgbdflsdhtgjdgfbdfgbdthstghfvcxvcvbmjhknfghdftgdthbdth
        + sdsgnsyjdtsaerynjfujfyuungfhdtstbdnbtydyjdbsatryuooortnaewAAWFADVSTSTHRTdthftyujnfdtgbrgbdftsdntgjdgfbdfgbdlhstghfvcxvcvbmjhkfghdftgdthddth
        + sdsgnsyjdtsaerynjfnujfyuungfhdlstbdnbtydyjdbsatryuooortnaewAAWFADVSTSTHRTdthftyujnfdjgbrgbdftsdntgjdgfbdfgbdlhstghfvcxvcvbmjhkfghdftgdthddt)
      {
        window.open('root.html','_self',false)
      }
     else
     {
       alert("Error: Password or Username")
      }
    }